### ISSUE TITLE
Question: where is the logic for distributing SWIV incentives?

### ISSUE THREAD

**Issue by webthethird** [Swivel-Finance/SSM#21]
Hello,

I am working on a safety module for another protocol, and doing research on how others implement it. In your docs, I see the following:
```
APR Explained
The yields that SSM stakers (stkSWIV holders) recieve are comprised of a number of revenue streams.
- Swivel Protocol Fees: The SSM earns 50% of all fees currently generated on the Swivel protocol. The fee share is variable dependent on future governance proposals.
- Balancer LP Fees: As all deposits are also providing liquidity, the SSM also earns all fees generated by an 80/20 Balancer pool comprised of SWIV/ETH.
- SWIV Incentives: Each epoch a given amount of SWIV are allocated in incentives to the SSM.
- External Incentives: Each Balancer Pool is eligible for incentives through balancers veBAL gauge system.
```
However, in the stkSWIV.sol contract I can't find any logic related to accruing SWIV rewards to stakers. For comparison, the Aave SM contains [this `_updateCurrentUnclaimedRewards` function](https://github.com/aave/aave-stake-v2/blob/7b706900e0e93fbb57ebd8580e51b472ccbd27e9/contracts/stake/StakedTokenV3.sol#L254). 

Where are the yields? Am I missing something?

**Comment by JTraversa** [comment]
For protocol fees, anything earned by Swivel is managed separately, where we purchase SWIV/ETH with proceeds and use the `donate` method (we could just send them to the safety module as well but this allows our backend to track donations). -- https://github.com/Swivel-Finance/SSM/blob/main/src/stkSWIV.sol#L704

Then for SWIV Incentives, we do all our calculations off-chain and utilize a modified merkle drop contract for continuous distribution --

https://github.com/Swivel-Finance/destributor/blob/main/build/Destributor.sol

This design allows us to combine multiple avenues of earning incentives (some from the safety module, some from our platform) into 1 merkle tree, and the modified distributor is a standard merkle drop that can be reused / which we overwrite every epoch.

++ Distributing protocol incentives in this way isolates the safety module to just dealing with BPTs -- if you otherwise wanted to keep the module just in BPTs, you would have to sell some of your incentives for ETH or whatever your pair might be.

**Comment by JTraversa** [comment]
Aaaand for balancer incentives, we plan to claim them using https://github.com/Swivel-Finance/SSM/blob/main/src/stkSWIV.sol#L782 which we then exchange into SWIV/ETH BPTs to `donate`

**Comment by webthethird** [comment]
I see, thanks for the clarification
